plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'docs/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/AnyInstance:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false