require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
